services:
  frontend:
    build: ./FrontEnd
    ports:
      - "5173:80"
    depends_on:
      - backend
      - flaskserver

  backend:
    build: ./BackEnd
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://threatsense:securepassword@db:5432/threatsense_db
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - db

  flaskserver:
    build: ./FlaskServer
    ports:
      - "7001:7001"
    environment:
      - DATABASE_URL=postgresql://threatsense:securepassword@db:5432/threatsense_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=threatsense
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=threatsense_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
